project:
  type: website

website:
  search: false
  title: "Sean Hoyt"
  navbar:
    background: primary
    left:
      - icon: github 
        href: https://github.com/sdhoyt
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/sean-hoyt-6b919570/
        aria-label: Linkedin
  page-footer: 
    border: false
    center:
      - href: https://quarto.org
        text: "Made with Quarto"
      - href: ""
        text: "__"
      - href: https://github.com/sdhoyt/website
        text: "Website Source" 
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

